#!/usr/bin/env python3
"""Generate and send r1-home VyOS configuration via API."""

import json
import subprocess
import sys

API_URL = "https://192.168.10.1/configure"
API_KEY = "BwAI"

commands = [
    # === System ===
    {"op": "set", "path": ["system", "time-zone", "Asia/Tokyo"]},
    {"op": "set", "path": ["system", "name-server", "127.0.0.1"]},
    # === DHCP static-mapping device-3 ===
    {
        "op": "set",
        "path": [
            "service",
            "dhcp-server",
            "shared-network-name",
            "main",
            "subnet",
            "192.168.10.0/24",
            "static-mapping",
            "device-3",
            "ip-address",
            "192.168.10.3",
        ],
    },
    {
        "op": "set",
        "path": [
            "service",
            "dhcp-server",
            "shared-network-name",
            "main",
            "subnet",
            "192.168.10.0/24",
            "static-mapping",
            "device-3",
            "mac",
            "88:c2:55:2f:d5:14",
        ],
    },
    # === DNS forwarding ===
    {
        "op": "set",
        "path": ["service", "dns", "forwarding", "listen-address", "127.0.0.1"],
    },
    {
        "op": "set",
        "path": ["service", "dns", "forwarding", "allow-from", "127.0.0.0/8"],
    },
    {
        "op": "set",
        "path": ["service", "dns", "forwarding", "allow-from", "192.168.11.0/24"],
    },
    {
        "op": "set",
        "path": ["service", "dns", "forwarding", "allow-from", "192.168.30.0/24"],
    },
    {
        "op": "set",
        "path": ["service", "dns", "forwarding", "allow-from", "192.168.40.0/22"],
    },
    {
        "op": "set",
        "path": ["service", "dns", "forwarding", "name-server", "59.190.147.97"],
    },
    {
        "op": "set",
        "path": ["service", "dns", "forwarding", "name-server", "59.190.146.145"],
    },
    # === Syslog (conntrack log forwarding to local server) ===
    {
        "op": "set",
        "path": [
            "system",
            "syslog",
            "host",
            "192.168.11.2",
            "facility",
            "local2",
            "level",
            "info",
        ],
    },
    # === SSH hardening ===
    {"op": "set", "path": ["service", "ssh", "disable-password-authentication"]},
    {"op": "set", "path": ["service", "ssh", "hostkey-algorithm", "ssh-ed25519"]},
    # === NAT destination (DNAT → main-pc 192.168.10.4) ===
    {
        "op": "set",
        "path": ["nat", "destination", "rule", "20", "description", "SoftEther-HTTP"],
    },
    {
        "op": "set",
        "path": [
            "nat",
            "destination",
            "rule",
            "20",
            "inbound-interface",
            "name",
            "pppoe0",
        ],
    },
    {"op": "set", "path": ["nat", "destination", "rule", "20", "protocol", "tcp"]},
    {
        "op": "set",
        "path": ["nat", "destination", "rule", "20", "destination", "port", "80"],
    },
    {
        "op": "set",
        "path": [
            "nat",
            "destination",
            "rule",
            "20",
            "translation",
            "address",
            "192.168.10.4",
        ],
    },
    {
        "op": "set",
        "path": ["nat", "destination", "rule", "30", "description", "SoftEther-HTTPS"],
    },
    {
        "op": "set",
        "path": [
            "nat",
            "destination",
            "rule",
            "30",
            "inbound-interface",
            "name",
            "pppoe0",
        ],
    },
    {"op": "set", "path": ["nat", "destination", "rule", "30", "protocol", "tcp"]},
    {
        "op": "set",
        "path": ["nat", "destination", "rule", "30", "destination", "port", "443"],
    },
    {
        "op": "set",
        "path": [
            "nat",
            "destination",
            "rule",
            "30",
            "translation",
            "address",
            "192.168.10.4",
        ],
    },
    {
        "op": "set",
        "path": ["nat", "destination", "rule", "40", "description", "iperf3-tcp"],
    },
    {
        "op": "set",
        "path": [
            "nat",
            "destination",
            "rule",
            "40",
            "inbound-interface",
            "name",
            "pppoe0",
        ],
    },
    {"op": "set", "path": ["nat", "destination", "rule", "40", "protocol", "tcp"]},
    {
        "op": "set",
        "path": ["nat", "destination", "rule", "40", "destination", "port", "5201"],
    },
    {
        "op": "set",
        "path": [
            "nat",
            "destination",
            "rule",
            "40",
            "translation",
            "address",
            "192.168.10.4",
        ],
    },
    {
        "op": "set",
        "path": ["nat", "destination", "rule", "50", "description", "iperf3-udp"],
    },
    {
        "op": "set",
        "path": [
            "nat",
            "destination",
            "rule",
            "50",
            "inbound-interface",
            "name",
            "pppoe0",
        ],
    },
    {"op": "set", "path": ["nat", "destination", "rule", "50", "protocol", "udp"]},
    {
        "op": "set",
        "path": ["nat", "destination", "rule", "50", "destination", "port", "5201"],
    },
    {
        "op": "set",
        "path": [
            "nat",
            "destination",
            "rule",
            "50",
            "translation",
            "address",
            "192.168.10.4",
        ],
    },
    # === NAT source (venue subnets masquerade) ===
    {
        "op": "set",
        "path": [
            "nat",
            "source",
            "rule",
            "110",
            "outbound-interface",
            "name",
            "pppoe0",
        ],
    },
    {
        "op": "set",
        "path": [
            "nat",
            "source",
            "rule",
            "110",
            "source",
            "address",
            "192.168.11.0/24",
        ],
    },
    {
        "op": "set",
        "path": [
            "nat",
            "source",
            "rule",
            "110",
            "translation",
            "address",
            "masquerade",
        ],
    },
    {
        "op": "set",
        "path": [
            "nat",
            "source",
            "rule",
            "120",
            "outbound-interface",
            "name",
            "pppoe0",
        ],
    },
    {
        "op": "set",
        "path": [
            "nat",
            "source",
            "rule",
            "120",
            "source",
            "address",
            "192.168.30.0/24",
        ],
    },
    {
        "op": "set",
        "path": [
            "nat",
            "source",
            "rule",
            "120",
            "translation",
            "address",
            "masquerade",
        ],
    },
    {
        "op": "set",
        "path": [
            "nat",
            "source",
            "rule",
            "130",
            "outbound-interface",
            "name",
            "pppoe0",
        ],
    },
    {
        "op": "set",
        "path": [
            "nat",
            "source",
            "rule",
            "130",
            "source",
            "address",
            "192.168.40.0/22",
        ],
    },
    {
        "op": "set",
        "path": [
            "nat",
            "source",
            "rule",
            "130",
            "translation",
            "address",
            "masquerade",
        ],
    },
    # === Firewall: WAN-LOCAL ===
    {
        "op": "set",
        "path": ["firewall", "ipv4", "name", "WAN-LOCAL", "default-action", "drop"],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LOCAL",
            "rule",
            "10",
            "action",
            "accept",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LOCAL",
            "rule",
            "10",
            "state",
            "established",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LOCAL",
            "rule",
            "10",
            "state",
            "related",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LOCAL",
            "rule",
            "20",
            "action",
            "accept",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LOCAL",
            "rule",
            "20",
            "protocol",
            "icmp",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LOCAL",
            "rule",
            "30",
            "action",
            "accept",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LOCAL",
            "rule",
            "30",
            "protocol",
            "tcp",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LOCAL",
            "rule",
            "30",
            "destination",
            "port",
            "22",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LOCAL",
            "rule",
            "30",
            "description",
            "SSH (ed25519 only)",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LOCAL",
            "rule",
            "40",
            "action",
            "accept",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LOCAL",
            "rule",
            "40",
            "protocol",
            "udp",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LOCAL",
            "rule",
            "40",
            "destination",
            "port",
            "51820",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LOCAL",
            "rule",
            "40",
            "description",
            "WireGuard from venue",
        ],
    },
    # === Firewall: WAN-LAN ===
    {
        "op": "set",
        "path": ["firewall", "ipv4", "name", "WAN-LAN", "default-action", "drop"],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LAN",
            "rule",
            "10",
            "action",
            "accept",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LAN",
            "rule",
            "10",
            "state",
            "established",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LAN",
            "rule",
            "10",
            "state",
            "related",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LAN",
            "rule",
            "20",
            "action",
            "accept",
        ],
    },
    {
        "op": "set",
        "path": ["firewall", "ipv4", "name", "WAN-LAN", "rule", "20", "state", "new"],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LAN",
            "rule",
            "20",
            "destination",
            "address",
            "192.168.10.4",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LAN",
            "rule",
            "20",
            "protocol",
            "tcp",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LAN",
            "rule",
            "20",
            "destination",
            "port",
            "80,443,5201",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LAN",
            "rule",
            "30",
            "action",
            "accept",
        ],
    },
    {
        "op": "set",
        "path": ["firewall", "ipv4", "name", "WAN-LAN", "rule", "30", "state", "new"],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LAN",
            "rule",
            "30",
            "destination",
            "address",
            "192.168.10.4",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LAN",
            "rule",
            "30",
            "protocol",
            "udp",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "name",
            "WAN-LAN",
            "rule",
            "30",
            "destination",
            "port",
            "5201",
        ],
    },
    # === Firewall: WANv6-LOCAL ===
    {
        "op": "set",
        "path": ["firewall", "ipv6", "name", "WANv6-LOCAL", "default-action", "drop"],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv6",
            "name",
            "WANv6-LOCAL",
            "rule",
            "10",
            "action",
            "accept",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv6",
            "name",
            "WANv6-LOCAL",
            "rule",
            "10",
            "state",
            "established",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv6",
            "name",
            "WANv6-LOCAL",
            "rule",
            "10",
            "state",
            "related",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv6",
            "name",
            "WANv6-LOCAL",
            "rule",
            "20",
            "action",
            "accept",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv6",
            "name",
            "WANv6-LOCAL",
            "rule",
            "20",
            "protocol",
            "icmpv6",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv6",
            "name",
            "WANv6-LOCAL",
            "rule",
            "30",
            "action",
            "accept",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv6",
            "name",
            "WANv6-LOCAL",
            "rule",
            "30",
            "protocol",
            "udp",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv6",
            "name",
            "WANv6-LOCAL",
            "rule",
            "30",
            "source",
            "port",
            "547",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv6",
            "name",
            "WANv6-LOCAL",
            "rule",
            "30",
            "destination",
            "port",
            "546",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv6",
            "name",
            "WANv6-LOCAL",
            "rule",
            "30",
            "description",
            "DHCPv6 replies",
        ],
    },
    # === Firewall: input filter ===
    {
        "op": "set",
        "path": ["firewall", "ipv4", "input", "filter", "default-action", "accept"],
    },
    {
        "op": "set",
        "path": ["firewall", "ipv4", "input", "filter", "rule", "10", "action", "jump"],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "input",
            "filter",
            "rule",
            "10",
            "jump-target",
            "WAN-LOCAL",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "input",
            "filter",
            "rule",
            "10",
            "inbound-interface",
            "name",
            "pppoe0",
        ],
    },
    # === Firewall: forward filter ===
    {
        "op": "set",
        "path": ["firewall", "ipv4", "forward", "filter", "default-action", "accept"],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "forward",
            "filter",
            "rule",
            "10",
            "action",
            "jump",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "forward",
            "filter",
            "rule",
            "10",
            "jump-target",
            "WAN-LAN",
        ],
    },
    {
        "op": "set",
        "path": [
            "firewall",
            "ipv4",
            "forward",
            "filter",
            "rule",
            "10",
            "inbound-interface",
            "name",
            "pppoe0",
        ],
    },
    # === Dummy interface (DHCPv6-PD receiver, address assigned by PD) ===
    {"op": "set", "path": ["interfaces", "dummy", "dum0"]},
    # === DHCPv6-PD → dum0 ===
    {
        "op": "set",
        "path": [
            "interfaces",
            "pppoe",
            "pppoe0",
            "dhcpv6-options",
            "pd",
            "0",
            "interface",
            "dum0",
            "sla-id",
            "0",
        ],
    },
    # === Static routes (venue subnets → wg0 peer) ===
    {
        "op": "set",
        "path": [
            "protocols",
            "static",
            "route",
            "192.168.11.0/24",
            "next-hop",
            "10.255.0.2",
        ],
    },
    {
        "op": "set",
        "path": [
            "protocols",
            "static",
            "route",
            "192.168.30.0/24",
            "next-hop",
            "10.255.0.2",
        ],
    },
    {
        "op": "set",
        "path": [
            "protocols",
            "static",
            "route",
            "192.168.40.0/22",
            "next-hop",
            "10.255.0.2",
        ],
    },
    # === BGP ===
    {"op": "set", "path": ["protocols", "bgp", "system-as", "65002"]},
    {
        "op": "set",
        "path": ["protocols", "bgp", "neighbor", "10.255.0.2", "remote-as", "65001"],
    },
    {
        "op": "set",
        "path": [
            "protocols",
            "bgp",
            "neighbor",
            "10.255.0.2",
            "description",
            "venue-r3",
        ],
    },
    {
        "op": "set",
        "path": [
            "protocols",
            "bgp",
            "neighbor",
            "10.255.0.2",
            "address-family",
            "ipv4-unicast",
        ],
    },
]

payload = {"key": API_KEY, "commands": commands}

print(f"Sending {len(commands)} commands to {API_URL}...")

result = subprocess.run(
    [
        "curl",
        "-sk",
        "--connect-timeout",
        "30",
        API_URL,
        "-X",
        "POST",
        "-H",
        "Content-Type: application/json",
        "-d",
        json.dumps(payload),
    ],
    capture_output=True,
    text=True,
    timeout=120,
)

print(result.stdout)
if result.returncode != 0:
    print(f"STDERR: {result.stderr}", file=sys.stderr)
    sys.exit(1)
